./flowtag_control fw clear
./flowtag_control fw add -swId 407 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 407 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 289 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 289 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 345 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 345 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 405 -hostId 2 -connectorId 3
./flowtag_control fw add -swId 405 -hostId 1 -connectorId 3
./flowtag_control fw add -swId 404 -hostId 2 -connectorId 3
./flowtag_control fw add -swId 404 -hostId 1 -connectorId 3
./flowtag_control fw add -swId 403 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 403 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 341 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 341 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 342 -hostId 2 -connectorId 3
./flowtag_control fw add -swId 342 -hostId 1 -connectorId 3
./flowtag_control fw add -swId 400 -hostId 2 -connectorId 3
./flowtag_control fw add -swId 400 -hostId 1 -connectorId 3
./flowtag_control fw add -swId 281 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 281 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 280 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 280 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 283 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 283 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 282 -hostId 2 -connectorId 4
./flowtag_control fw add -swId 282 -hostId 1 -connectorId 4
./flowtag_control fw add -swId 285 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 285 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 284 -hostId 2 -connectorId 3
./flowtag_control fw add -swId 284 -hostId 1 -connectorId 3
./flowtag_control fw add -swId 287 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 287 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 286 -hostId 2 -connectorId 3
./flowtag_control fw add -swId 286 -hostId 1 -connectorId 3
./flowtag_control fw add -swId 263 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 263 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 262 -hostId 2 -connectorId 3
./flowtag_control fw add -swId 262 -hostId 1 -connectorId 3
./flowtag_control fw add -swId 261 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 261 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 260 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 260 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 267 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 267 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 266 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 266 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 265 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 265 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 264 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 264 -hostId 1 -connectorId 4
./flowtag_control fw add -swId 269 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 269 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 268 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 268 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 423 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 423 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 422 -hostId 2 -connectorId 3
./flowtag_control fw add -swId 422 -hostId 1 -connectorId 3
./flowtag_control fw add -swId 425 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 425 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 424 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 424 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 379 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 379 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 378 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 378 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 416 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 416 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 417 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 417 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 410 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 410 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 411 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 411 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 298 -hostId 2 -connectorId 3
./flowtag_control fw add -swId 298 -hostId 1 -connectorId 3
./flowtag_control fw add -swId 299 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 299 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 296 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 296 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 297 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 297 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 294 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 294 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 295 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 295 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 292 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 292 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 293 -hostId 2 -connectorId 5
./flowtag_control fw add -swId 293 -hostId 1 -connectorId 5
./flowtag_control fw add -swId 290 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 290 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 291 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 291 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 319 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 319 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 318 -hostId 2 -connectorId 3
./flowtag_control fw add -swId 318 -hostId 1 -connectorId 3
./flowtag_control fw add -swId 313 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 313 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 312 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 312 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 311 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 311 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 310 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 310 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 317 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 317 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 316 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 316 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 315 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 315 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 314 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 314 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 270 -hostId 2 -connectorId 3
./flowtag_control fw add -swId 270 -hostId 1 -connectorId 3
./flowtag_control fw add -swId 271 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 271 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 391 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 391 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 273 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 273 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 274 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 274 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 275 -hostId 2 -connectorId 4
./flowtag_control fw add -swId 275 -hostId 1 -connectorId 4
./flowtag_control fw add -swId 276 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 276 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 277 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 277 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 278 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 278 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 279 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 279 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 399 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 399 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 398 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 398 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 414 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 414 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 415 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 415 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 429 -hostId 2 -connectorId 3
./flowtag_control fw add -swId 429 -hostId 1 -connectorId 3
./flowtag_control fw add -swId 428 -hostId 2 -connectorId 3
./flowtag_control fw add -swId 428 -hostId 1 -connectorId 3
./flowtag_control fw add -swId 447 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 447 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 368 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 368 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 369 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 369 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 421 -hostId 2 -connectorId 7
./flowtag_control fw add -swId 421 -hostId 1 -connectorId 7
./flowtag_control fw add -swId 420 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 420 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 364 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 364 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 365 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 365 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 362 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 362 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 363 -hostId 2 -connectorId 3
./flowtag_control fw add -swId 363 -hostId 1 -connectorId 3
./flowtag_control fw add -swId 427 -hostId 2 -connectorId 3
./flowtag_control fw add -swId 427 -hostId 1 -connectorId 3
./flowtag_control fw add -swId 361 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 361 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 308 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 308 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 309 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 309 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 406 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 406 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 440 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 440 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 412 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 412 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 300 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 300 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 301 -hostId 2 -connectorId 3
./flowtag_control fw add -swId 301 -hostId 1 -connectorId 3
./flowtag_control fw add -swId 302 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 302 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 303 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 303 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 304 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 304 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 305 -hostId 2 -connectorId 4
./flowtag_control fw add -swId 305 -hostId 1 -connectorId 4
./flowtag_control fw add -swId 445 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 445 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 307 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 307 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 380 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 380 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 371 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 371 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 382 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 382 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 383 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 383 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 384 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 384 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 385 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 385 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 386 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 386 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 387 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 387 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 388 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 388 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 389 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 389 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 443 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 443 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 444 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 444 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 373 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 373 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 306 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 306 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 372 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 372 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 360 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 360 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 381 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 381 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 418 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 418 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 374 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 374 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 377 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 377 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 438 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 438 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 439 -hostId 2 -connectorId 3
./flowtag_control fw add -swId 439 -hostId 1 -connectorId 3
./flowtag_control fw add -swId 436 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 436 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 437 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 437 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 393 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 393 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 435 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 435 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 432 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 432 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 433 -hostId 2 -connectorId 3
./flowtag_control fw add -swId 433 -hostId 1 -connectorId 3
./flowtag_control fw add -swId 430 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 430 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 431 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 431 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 339 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 339 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 338 -hostId 2 -connectorId 3
./flowtag_control fw add -swId 338 -hostId 1 -connectorId 3
./flowtag_control fw add -swId 450 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 450 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 334 -hostId 2 -connectorId 3
./flowtag_control fw add -swId 334 -hostId 1 -connectorId 3
./flowtag_control fw add -swId 452 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 452 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 336 -hostId 2 -connectorId 3
./flowtag_control fw add -swId 336 -hostId 1 -connectorId 3
./flowtag_control fw add -swId 331 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 331 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 330 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 330 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 333 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 333 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 332 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 332 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 258 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 258 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 259 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 259 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 442 -hostId 2 -connectorId 3
./flowtag_control fw add -swId 442 -hostId 1 -connectorId 3
./flowtag_control fw add -swId 413 -hostId 2 -connectorId 3
./flowtag_control fw add -swId 413 -hostId 1 -connectorId 3
./flowtag_control fw add -swId 256 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 256 -hostId 1 -connectorId 3
./flowtag_control fw add -swId 257 -hostId 2 -connectorId 6
./flowtag_control fw add -swId 257 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 344 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 344 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 288 -hostId 2 -connectorId 3
./flowtag_control fw add -swId 288 -hostId 1 -connectorId 3
./flowtag_control fw add -swId 346 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 346 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 347 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 347 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 340 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 340 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 402 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 402 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 401 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 401 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 370 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 370 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 343 -hostId 2 -connectorId 3
./flowtag_control fw add -swId 343 -hostId 1 -connectorId 3
./flowtag_control fw add -swId 366 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 366 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 392 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 392 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 348 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 348 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 272 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 272 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 349 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 349 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 446 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 446 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 390 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 390 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 409 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 409 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 397 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 397 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 408 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 408 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 396 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 396 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 395 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 395 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 449 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 449 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 394 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 394 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 426 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 426 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 375 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 375 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 448 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 448 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 441 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 441 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 322 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 322 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 323 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 323 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 320 -hostId 2 -connectorId 4
./flowtag_control fw add -swId 320 -hostId 1 -connectorId 4
./flowtag_control fw add -swId 321 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 321 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 326 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 326 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 327 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 327 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 324 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 324 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 325 -hostId 2 -connectorId 3
./flowtag_control fw add -swId 325 -hostId 1 -connectorId 3
./flowtag_control fw add -swId 328 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 328 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 329 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 329 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 335 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 335 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 367 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 367 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 419 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 419 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 434 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 434 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 451 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 451 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 357 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 357 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 356 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 356 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 355 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 355 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 354 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 354 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 353 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 353 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 352 -hostId 2 -connectorId 3
./flowtag_control fw add -swId 352 -hostId 1 -connectorId 3
./flowtag_control fw add -swId 351 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 351 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 350 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 350 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 337 -hostId 2 -connectorId 1
./flowtag_control fw add -swId 337 -hostId 1 -connectorId 1
./flowtag_control fw add -swId 376 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 376 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 359 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 359 -hostId 1 -connectorId 2
./flowtag_control fw add -swId 358 -hostId 2 -connectorId 2
./flowtag_control fw add -swId 358 -hostId 1 -connectorId 2
